# Generated by Django 3.2.12 on 2022-03-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SOME STRING', max_length=200, verbose_name='имя записи')),
                ('uploadedFile', models.FileField(upload_to='Uploaded Files/')),
                ('sender', models.CharField(default='SOME STRING', max_length=200, verbose_name='имя аккаунта')),
            ],
        ),
    ]
