# Generated by Django 3.2.12 on 2022-03-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texttospeech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotext',
            name='namefile',
            field=models.CharField(default='SOME STRING', max_length=200, verbose_name='имя файла'),
        ),
        migrations.AlterField(
            model_name='audiotext',
            name='uploadedFile',
            field=models.CharField(default='SOME STRING', max_length=200, verbose_name='путь до файла'),
        ),
    ]
