# Generated by Django 3.2.12 on 2022-03-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texttospeech', '0002_auto_20220303_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotext',
            name='recipients',
            field=models.TextField(default='', verbose_name='получатели записи'),
        ),
        migrations.AlterField(
            model_name='audiotext',
            name='namefile',
            field=models.CharField(default='', max_length=200, verbose_name='имя файла'),
        ),
        migrations.AlterField(
            model_name='audiotext',
            name='sender',
            field=models.CharField(default='', max_length=200, verbose_name='имя аккаунта'),
        ),
        migrations.AlterField(
            model_name='audiotext',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='имя записи'),
        ),
        migrations.AlterField(
            model_name='audiotext',
            name='uploadedFile',
            field=models.CharField(default='', max_length=200, verbose_name='путь до файла'),
        ),
    ]
