# Generated by Django 3.2.12 on 2022-03-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='recipients',
            field=models.TextField(default='', verbose_name='получатели записи'),
        ),
        migrations.AddField(
            model_name='count',
            name='sender',
            field=models.CharField(default='SOME STRING', max_length=200, verbose_name='имя аккаунта'),
        ),
        migrations.AddField(
            model_name='count',
            name='text',
            field=models.TextField(default='', verbose_name='распознанный текст'),
        ),
    ]
