# Generated by Django 3.2.12 on 2022-02-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='dateTimeOfUpload',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
