# Generated by Django 3.2.12 on 2022-02-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_auto_20220222_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст записи')),
            ],
        ),
    ]
