# Generated by Django 3.2.12 on 2022-02-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_textaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='textaudio',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=200, verbose_name='имя записи'),
        ),
    ]
