# Generated by Django 3.2.12 on 2022-03-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0005_textaudio_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='textaudio',
            name='recipients',
            field=models.TextField(default='SOME STRING', verbose_name='получатели записи'),
        ),
    ]
