# Generated by Django 3.2.12 on 2022-03-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0006_textaudio_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textaudio',
            name='recipients',
            field=models.TextField(default='', verbose_name='получатели записи'),
        ),
    ]
